export const hotelTypes = [
  "Luxury Hotel",
  "Boutique Hotel",
  "Budget Hotel",
  "Resort",
  "Business Hotel",
  " B&B",
  "Hostel",

  "Boutique Resort",
  "Eco-Hotel",
  "Airport Hotel",
  "Spa Hotel",
  "Casino Hotel",
  "Pet-Friendly ",
  "All-Inclusive ",
  "Historic Hotel",
];

export const hotelFacilities = [
  "Free Wi-Fi",
  "Swimming Pool",
  "Fitness Center",
  "Spa and Wellness Center",
  "Restaurant",
  "Bar/Lounge",
  "Room Service",
  "24-Hour Front Desk",
  "Airport Shuttle",
  "Parking",
  "Business Center",
  "Conference Facilities",
  "Laundry Service",
  "Pet Friendly",
  "Family Rooms",
  "Non-smoking Rooms",
  "Wheelchair Accessible",
  "Garden",
  "Terrace",
  "Beachfront",
  "Ski Storage",
  "Bicycle Rental",
  "Kids Club",
  "Entertainment Staff",
  "Currency Exchange",
  "Tour Desk",
  "Safety Deposit Box",
  "Elevator",
  "Designated Smoking Area",
];

export const bedTypes = [
  { name: "Single Bed", info: "(90-130cm)" },
  { name: "Double Bed", info: "(131-150cm)" },
  { name: "King Size", info: "(151-180cm)" },
  { name: "Super-king size", info: "(181 - 210 cm)" },
];

export const roomTypes = [
  "Single Room",
  "Double Room",
  "Twin Room",
  "Triple Room",
  "Quadruple Room",
  "Family Room",
  "Suite",
  "Studio",
  "Apartment",
  "Deluxe Room",
  "Executive Room",
  "Penthouse",
  "Loft",
  "Bungalow",
  "Villa",
];

export const roomNames = [
  "Standard Double Room",
  "Deluxe King Room",
  "Family Suite",
  "Executive Suite",
  "Single Room",
  "Twin Room",
  "Superior Double Room",
  "Junior Suite",
  "Queen Room",
  "Penthouse Suite",
  "Budget Double Room",
  "Triple Room",
  "Luxury Suite",
  "Classic Room",
  "Studio Apartment",
  "Honeymoon Suite",
  "Villa",
  "Bungalow",
  "Dormitory Room",
  "Presidential Suite",
  "Standard Twin Room",
  "Superior King Room",
  "Economy Single Room",
  "Deluxe Queen Room",
  "Family Room",
  "Superior Family Room",
];

export const roomAmenities = [
  "Free WiFi",
  "Air Conditioning",
  "Flat-screen TV",
  "Minibar",
  "Private Bathroom",
  "Hairdryer",
  "Tea/Coffee Maker",
  "Ironing Facilities",
  "Safety Deposit Box",
  "Desk",
  "Seating Area",
  "Sofa",
  "Wardrobe or Closet",
  "Balcony",
  "Terrace",
  "Soundproofing",
  "Kitchenette",
  "Refrigerator",
  "Microwave",
  "Electric Kettle",
  "Kitchenware",
  "Oven",
];
